extraction:
  cpp:
    after_prepare: 
      - python report.py 18
  cobol:
    after_prepare: 
      - python report.py 18
  csharp:
    after_prepare: 
      - python report.py 18
  java:
    after_prepare: 
      - python report.py 18
  javascript:
    after_prepare: 
      - python report.py 18
  python:
    after_prepare: 
      - python report.py 18
